name: MultiverseCreatures
version: '${project.version}'
main: com.Chagui68.MultiverseCreatures
api-version: '1.21'
load: STARTUP
author: Chagui68
description: A themed creatures and items plugin 
website: https://github.com/Chagui68/MultiverseCreatures
softdepend: []

commands:
  msc:
    description: Main command for MultiverseCreatures
    usage: /msc <spawn|damage|ability|chests|check>
    permission: msc.admin
